<header  id="overview">
    <h1 >Kaerdon <span>Welcome</span> you</h1>
    <h2 class="lead">This is the website for all NFTs collections by <span>kaerdon</span></h2>
    <hr class="my-4">
</header>

<div class="row">
    <div class="col-md-12 col-lg-4">
                <h3>The mysteries tarots cards collection</h3>
                <p>This collection of unique tarots cards with differents characteristics </p>

    </div>

    <div class="col-md-12 col-lg-4">
        <h3>Mysteries tarots cards gallery</h3>
        ArcanaMajoris Edition!
        <img src="img/arcanamajoris.gif" width="154px" height="270px">
        <?php echo $this->tag->linkTo(['/nftcollection/show/arcanamajoris', 'view ArcanaMajoris', 'class' => 'btn btn-primary']); ?>
        
    </div>

    <div class="col-md-12 col-lg-4">
        <h3>NFT-artists-alliance</h3>
        <address>
            <strong>1proamonservice</strong><br>
            42, rue de la platinerie,<br>
            7110 Houdeng-Aimeries<br>
            Belgique<br>
            <abbr title="Phone">Phone:</abbr>&nbsp;<a href="tel:+32456232272" title="Call us">+32 456232272</a>
        </address>
        <address>
            <strong>Contacts</strong><br>
            <a href="mailto:tim@1proamonservice.eu?subject=kaerdon nft" title="Send feedback">tim@1proamonservice.eu</a>
        </address>
    </div>
</div>
