<div class="d-flex flex-row bd-highlight mb-3">
    <div class="p-2 bd-highlight">
        <h2>The team <span>Kaerdon</span> welcome you</h2>
        <img  src="../img/kaerdon2.png" class="curve">
        
        <p>You're now flying with Kaerdon. <br>Great things are about to happen! <br>A guardian, a protector,<br>a teacher and a student<br>
        </p>
        
        <p >I'm Kaerdon the <span>messenger</span> of the <span>gods</span> <br>Bound by purpose to this <span>humanity</span> and <span>universe</span></p>
        <p>A long time ago, <br>very long in your time, <br>barely a whisper in mine, <br>I came onto this world</p>
        <p></p>
        <h3>An <span>old song</span> for a <span>very old story</span></h3>
        <p>As some strange legends, come back and forth time to time.<br>Kaerdon comes from the collective unconscious<br> to the surface through art, songs, and text.<br>
            One of the last time this occur was in the middle of the 90's in a song <br>from a belgian band called
            scatophagus</p>
           
            
    </div>
    
    <div class="p-2 bd-highlight">
        <div class="three">
         
        </div>
    </div>
    <div class="p-2 bd-highlight">
        <div class="two">
        
        </div>
    </div>
    
   
</div>
 