<div class="d-flex flex-row bd-highlight mb-3">
    <div class="p-2 bd-highlight">
        <h2><span>Kaerdon</span> welcome you</h2>
        <img  src="../img/kaerdon2.png" class="curve">
        
        <p>You're now flying with Kaerdon. <br>Great things are about to happen! <br>A guardian, a protector,<br>a teacher and a student<br>
        </p>
        
        <p >I'm Kaerdon the <span>messenger</span> of the <span>gods</span> <br>Bound by purpose to this <span>humanity</span> and <span>universe</span></p>
        <p>A long time ago, <br>very long in your time, <br>barely a whisper in mine, <br>I came onto this world</p>
        <p></p>
        <h3>An <span>old song</span> for a <span>very old story</span></h3>
        <p>As some strange legends, come back and forth time to time.<br>Kaerdon comes from the collective unconscious<br> to the surface through art, songs, and text.<br>
            One of the last time this occur was in the middle of the 90's in a song <br>from a belgian band called
            scatophagus</p>
           
            
    </div>
    
    <div class="p-2 bd-highlight">
        <div class="three">
        <h3> I will be born</h3>
        In the beginning of world<br>
        was born a son of God<br>
        he was called Kaerdon<br>
        he know the past and the futur<br>
        he receive the feeling of peace and love <br>
        he must just be a teacher of human<br>
        he come on our world<br>
        I'm Kaerdon the guardian of peace and protector of love<br>
        as long as i live i will teach the human being in the way of light.<br>
        so many secret are inside your heart<br>
        This is the way of love and immortality, it's a way of pure love<br>
        Clean your mind<br>
        by the power of your love destroy your ego<br>
        choosing my way the way of light<br>
        The power is the extreme control of your mind<br>
        that control must be directly from you heart to be good<br>
        please ear me to save your life from the dark lords of the earth<br>
        <iframe width="280" height="157" src="https://www.youtube.com/embed/qxG_smL0a-c" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
    </div>
    <div class="p-2 bd-highlight">
        <div class="two">
        
        Unconsciousness is the better weapon of dark lords<br>
        Ear the voice of dream and be.<br>
        now you have the real power<br>
        I teach the way of light<br>
        The good way pass by the love<br>
        just walk that way or perish<br>
        in the way of light <br>
        i know your futur <br>
        ear me and believe me<br>
        you will be my parents<br>
        unconsciousness is the better weapon of dark lords<br>
        Ear the voice of dream and be.<br>
        now you have the real power<br>
        I teach the way of light<br>
        The good way pass by the love<br>
        just walk that way or perish<br>
        in the way of light <br>
        i know your futur <br>
        ear me and believe me<br>
        you will be my parents<br>
        </div>
    </div>
    
   
</div>
 