<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <title>Kaerdon welcome you</title>

    <?php $this->assets->outputCss(); ?>
</head>
<body class="d-flex flex-column h-100">
   

<nav class="navbar navbar-expand-lg navbar-dark ">
    <?php echo $this->tag->linkTo([null,'Kaerdon' ,'class' =>'navbar-brand']); ?>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <?php foreach( $menus as $key => $value)  {
                if ($value == $this->dispatcher->getControllerName()){ ?>
                <li class="nav-item active">
                    <?php echo $this->tag->linkTo([$value,  $key, 'class'=> 'nav-link']); ?>
                </li>
               <?php } else { ?>
                <li class="nav-item"><?php echo $this->tag->linkTo([$value,  $key, 'class'=> 'nav-link']); ?></li>
               <?php }
            } ?>
        </ul>

        <ul class="navbar-nav  my-2 my-lg-0">
        <?php if ($this->session->is_logged ==='true') { ?>
            <li class="nav-item"> <input class="btn-primary" id="connectButton" type="button" value="Connect" ></li>
            <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-expanded="false">
            <?php echo 'Hello '.$this->session->user->name;?>
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <li class="nav-item"><?php echo $this->tag->linkTo(['profile','Profile', 'class'=> 'nav-link']); ?></li>
            <li class="nav-item"><?php echo $this->tag->linkTo(['session/logout','Logout', 'class'=> 'nav-link']); ?></li>
          </ul>
        </div>
            
        <?php } else { ?>
            <li class="nav-item"> <input class="btn-primary" id="connectButton" type="button" value="Connect" ></li>
            <li class="nav-item"><?php echo $this->tag->linkTo(['session','Login', 'class'=> 'nav-link']); ?></li>
        <?php } ?>
        </ul>
    </div>
</nav>

<main role="main" class="flex-shrink-0 h-100">
    <div class="container h-100">
    <section id="home" class="gray_bg parallax_banner h-100">
				<div class="welcome-slider-area">
					<div class="single-slide-item">
						<div id="particles-js"><canvas class="particles-js-canvas-el h-100" >                    
                       </canvas></div>
                       <div class="single-slide-item-table">
							<div class="single-slide-item-tablecell">
								
									<div class="row">
										<div class="col-md-12"><?php echo $this->getContent(); ?>    
											<div class="slider_title_animation_right"> </div>
											<!--
                                            <p class="wow fadeInRight" data-wow-duration="1s" data-wow-delay="0.5s" data-wow-offset="0" style="visibility: visible; animation-duration: 1s; animation-delay: 0.5s; animation-name: fadeInRight;">We provides always our best services for our partners and  always<br> try to achieve making a bright successful future</p>
											 
                                            
											<div class="single_slide_item_button wow fadeInUp" data-wow-duration="1s" data-wow-delay="1s" data-wow-offset="0">
												<a href="#" class="slider_btn s_bg_btn">Read More</a>
												<a href="#" class="slider_btn">Contact Us</a>
											</div>
											-->
										</div>
									</div>
								
							</div>
						</div>
					</div>
				</div>
			</section>
    
    
       
    </div>
</main>

<footer class="footer mt-auto ">
    <div class="container">
        <span class="text-muted">
            <span style="color:#00FF00;">Made with Phalcon by  <a href="https://1proamonservice.eu/">1proamonservice.eu</a>
            <?php echo $this->tag->linkTo("privacy", "Privacy Policy");
             echo $this->tag->linkTo("terms", "Terms"); ?>

            © <?php echo date("Y")." "; echo $this->tag->linkTo("https://nft-artists-alliance.eu/", "nft-artists-alliance", false); ?></span>
        </span>
    </div>
</footer>
<?php $this->assets->outputJs(); ?>  
<script>window.addEventListener('DOMContentLoaded', initialize); </script>
<!-- Particles js 
<script src="js/particles.min.js"></script>
<script src="js/app.js"></script>
-->


    
    
</body>
</html>
